### ISSUE TITLE
Critical security vulnerability due to insufficient key size

### ISSUE THREAD

**Issue by maqp** [jq-rs/mles-webworker#10]
As per [the Reddit discussion](https://www.reddit.com/r/privacy/comments/ec8jmh/whatsapp_messaging_replacement/fba6y1d), mles system uses a 56-bit keys which have been considered insecure at least for the past 22 years, i.e. since EFF [broke](https://en.wikipedia.org/wiki/EFF_DES_cracker) the [DES](https://en.wikipedia.org/wiki/Data_Encryption_Standard) algorithm that also used 56-bit keys.

**Comment by jq-rs** [comment]
Thanks for the issue! It is true that 56-bit offers only low level of security, this has been updated now to the README for users who are not that security aware.

**Comment by jq-rs** [comment]
After some investigation, 56-bit is indeed surprisingly weak as there can be precalculated tables for all key values.

Now completely removed all references to encryption via 103c9e5c741c1633113a301ee34af9c5b4906aa0 and 4ba2861996270b8202b2fd51b4cc9e9a1565bb11.  Same is done to documentation elsewhere. Closing.

**Comment by jq-rs** [comment]
TLS support included and clarified the reasons to use weak encryption on README.

**Comment by maqp** [comment]
>However, to get to this “published” and uncontrolled state, the exporter must notify the U.S. Department of Commerce's Bureau of Industry and Security (BIS) and the ENC Encryption Request Coordinator at the National Security Agency with either:

>    the URL or internet address where the encryption source code has been published, or
    a copy of the published encryption source code.

>The notification or copy should be sent to crypt@bis.doc.gov and to enc@nsa.gov.

>It should also be noted that updates to encryption source code may trigger a requirement to provide additional copies to both BIS and NSA. If you have provided a copy of the published source code, then you must notify the government again when the cryptographic functionality of the source code is updated or modified. If you have posted the source code on the Internet, then you don’t have to provide notice of changes to the encryption functionality, but you do have to notify BIS and the ENC Encryption Request Coordinator each time the Internet location is changed. For all of these notices, exporters should use the same email addresses: crypt@bis.doc.gov and to enc@nsa.gov.

>**If these requirements seem like empty bureaucratic formalism to you, we agree. There is even a good argument that the regulations are still unconstitutional. But we’re happy that the government has not tried to impose heavy export burdens to re-regulate encryption. We’d also point to a now nearly-two-decade-long track record of open source encryption publishers being free of harassment under the EAR.**

Why not instead implement strong encryption suite, send the e-mails about your product as a formality, and add the standard disclaimer: https://github.com/signalapp/Signal-iOS#cryptography-notice for Wassenaar. (Note: IANAL, and considering US is a litigation nation, consult an actual lawyer first to not get into trouble).

**Comment by jq-rs** [comment]
The feedback from current users is against it (as they do not want to end up into automated tools).

Still, an option later on is to have a new application with strong enc which can be selected by those users who prefer that path.

**Comment by jq-rs** [comment]
Some more insights to Blowfish and key length [using_56bit_blowfish_to_avoid_getting_caught_in](https://www.reddit.com/r/programminghorror/comments/ex87s5/using_56bit_blowfish_to_avoid_getting_caught_in/fg8isym).

**Comment by jq-rs** [comment]
AES forwarding is now added to proxy: https://github.com/jq-rs/arki-server/commit/718ea3151fa7f169541b07db424d1c6a56cc9204. With AES proxy, obfuscated data is never transmitted as such to line and is never part of, possibly remote, Mles server history data.

**Comment by jq-rs** [comment]
An alternative webworker example implementation with a larger key size is now available [here](https://github.com/ZpincDev/zpinc-webworker) with an article as background info for those interested.
